repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
      - id: poetry-check
#      - id: poetry-lock
#      - id: poetry-export

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

#-   repo: https://github.com/mwouts/jupytext
#    rev: v1.15.1  # CURRENT_TAG/COMMIT_HASH
#    hooks:
#    - id: jupytext
#      args: [--sync]
