services:

  notebook:
    build: .
    command: jupyter lab --ip='0.0.0.0' --port=8888 --no-browser
    ports:
      - "8888:8888"
    volumes:
      - .:/code/
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [ gpu ]
